//  Code generated by oto; DO NOT EDIT.

import http.client


// service: AccessKeyService
    
//     method: GenerateKey
    

// service: AutocompleteService
    
//     method: CheckIndexName
    
//     method: CheckIndexPath
    
//     method: Complete
    
//     method: CreateIndex
    
//     method: DeleteDoc
    
//     method: DeleteIndex
    
//     method: GetIndex
    
//     method: GetIndexes
    
//     method: PutDoc
    

// service: IndexService
    
//     method: CheckIndexName
    
//     method: CheckIndexPath
    
//     method: CreateIndex
    
//     method: DeleteDoc
    
//     method: DeleteIndex
    
//     method: GetIndex
    
//     method: GetIndexes
    
//     method: PutDoc
    
//     method: Search
    
